springboard (basically)
Do not attempt to divide by 0 if max == min

    == Request: /blog/tag/index.html
           error  build/blog/tag/index.html
    divided by 0
    /home/fedora/atomic-site/source/tag.html.haml:36:in `/'
    /home/fedora/atomic-site/source/tag.html.haml:36:in `tag_size'
    /home/fedora/atomic-site/source/tag.html.haml:49:in `block (2 levels) in singleton class'
    /home/fedora/atomic-site/source/tag.html.haml:48:in `each'
    /home/fedora/atomic-site/source/tag.html.haml:48:in `block in singleton class'
    /home/fedora/atomic-site/source/tag.html.haml:-18:in `instance_eval'
    /home/fedora/atomic-site/source/tag.html.haml:-18:in `singleton class'
    /home/fedora/atomic-site/source/tag.html.haml:-20:in `__tilt_18972300'

It happen if you have 1 single blog post with 1 tag. Since count
would also be equal to min, the size will always be 100% for all tags.

slightly tweaked README headers

commented out favicon generation (and added a note that ImageMagick is needed)

handle the case where tags do not exist

demote tag page headings to H2

add in a couple more asciidoc settings

Do not fail if there is only blog post in the future

This manifest with the following traceback :
       error  build/blog/feed.xml
  undefined method `date' for nil:NilClass
  /home/fedora/atomic-site/source/feed.xml.builder:10:in `block (2 levels) in singleton class'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
  /home/fedora/.gem/ruby/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing

The cause is that blog.articles.first will be Nil if there is no blog
post and yet the blog exist ( since there is article to be published )

fix the icon generation for newer version of the favicon_maker extension

Conflicts:
	config.rb

added mixins for greyscale filtering & responsive images

fixed more-link classes for blog posts

added a "tail" section to hook in simple per-page JS via yield

be sure to check that source has items too (before doing an each)

header logo shouldn't have rhlogo as the ID

added simple shell scripts

pass arguments from the command to the middleman server (for --port, etc.)

created LICENSE.md file

added flexbox-based sticky footer

generate favicon on build

use page_classes variable from page's frontmatter in <body>

don't use doc browser for documentation

new versions seem to add asciidoc now

added font-awesome

added fallback support for SVG

Added .cache to the gitignore

switch from RedCarpet to Kramdown for Markdown

added middleman-pry; better debugging in `bundle exec middleman console`

don't include glyphicons in bootstrap (we're using font-awesome now)

upgrade all the things (notable: middleman 3.3.x & sass 3.3.x)

update submodule on every build & dev server start

added submodule commands to the setup script

force a submodule sync after the forced init. "yay, git submodules!"

removed redundant helpers

added helpers to grab a Markdown doc & display a table of contents

Table of contents will either be from the rendered document, or it will
be generated by H2s if an in-page ToC doesn't exist.

added html_to_plaintext helper function

fixed 404 page a bit

fixed blog post to be compatible with Bootstrap 3.3.x

fixed title auto page title (with document title-from-header discovery)

properly handle empty page title addon overrides

use html_to_plaintext in discover_title, to weed out HTML in headings

upgraded all the gems to their most recent versions

don't include juvia comment CSS by default

post-meta shouldn't extend container

added padding for footer in the barebones default site "theme"

disabled bootstrap JS by default (uncomment items to selectively turn on)

added feed handling gem

added support for simple RSS/Atom feed parsing & displaying (as list)

updated compass and a few deps

Updated commands in README.md

add patch, as nokogiri requires it to build

missing exec in Adding a Post example

handle CSV list of tags

use blog post date, regardless of metadata or filename-specified

added support for paramaters to display content only

added markdown editor

ported editor to sass; heavily customized it for our needs

first version of admin UI

ignore administration UI at build time

use absolute link for editing

disable livereload for the edit page

added draft support to blog listing & XML

added a (hardcoded) notice with a link to the admin section

added better draft support when saving articles

re-enabled save on form change

This was disabled eariler for debugging and I didn't mean to commit the
commenting out. Oops!

fixed published detection in edit

fixed comments detection in edit

added new post functionality

big overhaul for the index page (sorry for many features in 1 commit)

changed JS/CSS

adjust JS & CSS for admin section

added standard application JS

added headerbar to blog editing

added rename & delete dialogs

minor adjustments of author and date fields

reorg'd functions

save when window loses focus or is closed

shut down LiveReload on the index page

changed save URL to point to /admin/save/

added style to newpost page & a slight delay to prevent a race condition

removed trailing slash from edit URL to make it consistent w/ index

focus the editor by default

added focus/blur support for codemirror

added a bit of class to the forms

turn off autocomplete on the filter form

(it gets in the way)

added wordcount in the blog listing

admin style tweaks

removed extra padding on the editor

added author dropdown & current date button

made combo box's default reflect current blog post

disable datetime editing for now, as it currently messes things up

increased delay time to prevent a post issue

reworked saving to support renames (= date + slug changes)

made date a variable and check for it on JSONification

added preliminary (& basic) git support

added deletion functionality

ajaxified new post creation

commented out ajax stopper

use .html.md, not just plain .md

check for meta & content

re-enable ajax aborting

removed debug output

added the delete action

(oops!)

fixed setting date to now

moved blog edit SASS to admin sass file

don't create a page when there's no title

handled the case where someone clicks on create post w/ no title

added title & page classes

added headers

added a little space between rename & delete

added a touch of contrast for editor's button text

moved ajax actions to api subdir

changed blog date check to use "defined?"

normalize time to UTC

added a header bar to the main admin page

ensure admin works with all sites, regardless of style

reworked spacing for new blog post (ensuring helper tip shows up)

support comma-separated tags in addition to an array, in feeds

use jquery gem from rails-assets

handle DOS-formatted files

we're not using iframes for previewing anymore

An initial version used iframes for previewing.

This left-over CSS was interfering with videos in the preview.

remove admin.js from the build step (as it's only used in dev)

remove pry-debugger

added create-post.rb: it creates a post, opens it in $EDITOR & browser

support tags

default to displaying help when no title is provided

self-reference create-post script command

override blog date to gracefully fallback when file & metadata differ

added classes to navigation links

added search functionality

handle multi-line auto-titles

added markdown support for author blurbs (incl. auto-twitter-linking)

TZ fix for date

fixed timezone output

added a save button in the admin UI

added jquery.cookie

split out basic from layout; added admin template

Both layout and admin depend on basic. Any page can include any of these
templates... basic comes w/o the site-specific branding, for times when
that's needed.

admin index still uses "layout", but now header & footer aren't rendered

I plan to port this to the admin layout in the not-too-distant-future.

remember the author selection in the blog post creation

remove "server" so other commands (ex: build, deploy) can be used too

changed configs based on rubocop suggestions

several adjustments, as suggested by rubocop

fixed link to Middleman docs in the README

Thanks to @apevec for pointing out Middleman's link change!

layout wrapping needs to be output, hence "~"

This is related to a change in (upstream) Middleman

has_key? shouldn't be ambiguous (needs parenthesis here)

added back middleman's page_classes helper (oops)

admin needs i18n enabled in some circumstances (for relative dates)

extend 404 with a search based on the URL